### ISSUE TITLE
Problem: The README.md file misspells "ManiCore"

### ISSUE THREAD

**Issue by ttmc** [0xdefaceme/whitepaper#17]
The [README.md](https://github.com/0xdefaceme/whitepaper/blob/master/README.md) file refers to:

> TrailOfBits's ManiCore [5]

but the correct spelling (and styling) is "Manticore" (with no capital 'C'). Here are some more specific references that could be used in place of the current one at [5]:

- https://github.com/trailofbits/manticore
- https://blog.trailofbits.com/2017/04/27/manticore-symbolic-execution-for-humans/

Also, if you're curious what a manticore is, see https://en.wikipedia.org/wiki/Manticore

**Comment by TimDaub** [comment]
Thx, fixed in https://github.com/0xdefaceme/whitepaper/commit/6c2f91610fb9ca6ea4996266af7d73b98b9c950e
